define(function () {

    'use strict';

    return {

        //1= indicator id
        "1_filter-dd_filter_item_1" :  [],
        "1_filter-dd_filter_item_2" : ["1"],
        "1_filter-dd_filter_item_3" : ["1"],
        "1_filter-dd_filter_item_4_1" : [],
        "1_filter-dd_filter_item_4_2" : [],
        "1_filter-dd_filter_item_4_3" : ["744"],
        "1_filter-dd_filter_item_4_4" : ["826"],
        "1_filter-dd_filter_item_5" : ["1"],
        "1_filter-dd_filter_item_6" : ["1"],
        "1_filter-dd_filter_item_7_1" : [],
        "1_filter-dd_filter_item_7_2" : ["36"],
        "1_filter-dd_filter_item_8" : ["20"],
        "1_filter-dd_filter_item_9" : ["1"],
        "1_filter-dd_filter_item_10" : [],
        "1_filter-dd_filter_item_11" : ["1"],
        "1_filter-dd_filter_item_12" : ["1", "2", "3"],

        //2= indicator id
        "2_filter-dd_filter_item_1" :  [],
        "2_filter-dd_filter_item_2" : ["1"],
        "2_filter-dd_filter_item_3" : ["1"],
        "2_filter-dd_filter_item_4_1" : [],
        "2_filter-dd_filter_item_4_2" : [],
        "2_filter-dd_filter_item_4_3" : ["744"],
        "2_filter-dd_filter_item_4_4" : ["826"],
        "2_filter-dd_filter_item_5" : ["1"],
        "2_filter-dd_filter_item_6" : ["1"],
        "2_filter-dd_filter_item_7_1" : [],
        "2_filter-dd_filter_item_7_2" : ["36"],
        "2_filter-dd_filter_item_8" : [],
        "2_filter-dd_filter_item_9" : ["1"],
        "2_filter-dd_filter_item_10" : ["1"],
        "2_filter-dd_filter_item_11" : ["1", "2", "3"],

        ///3= indicator id
        "3_filter-dd_filter_item_1" :  [],
        "3_filter-dd_filter_item_2" : ["1"],
        "3_filter-dd_filter_item_3" : ["1"],
        "3_filter-dd_filter_item_4_1" : [],
        "3_filter-dd_filter_item_4_2" : [],
        "3_filter-dd_filter_item_4_3" : ["744"],
        "3_filter-dd_filter_item_4_4" : ["826"],
        "3_filter-dd_filter_item_5" : ["1"],
        "3_filter-dd_filter_item_6" : ["1"],
        "3_filter-dd_filter_item_7_1" : [],
        "3_filter-dd_filter_item_7_2" : ["36"],
        "3_filter-dd_filter_item_8" : [],
        "3_filter-dd_filter_item_9" : ["1"],
        "3_filter-dd_filter_item_10" : [],
        "3_filter-dd_filter_item_11" : ["1"],
        "3_filter-dd_filter_item_12" : ["1", "2", "3"],

        //10= indicator id
        "4_filter-dd_filter_item_1" :  [],
        "4_filter-dd_filter_item_2" : ["1"],
        "4_filter-dd_filter_item_3" : ["1"],
        "4_filter-dd_filter_item_4_1" : [],
        "4_filter-dd_filter_item_4_2" : [],
        "4_filter-dd_filter_item_4_3" : ["744"],
        "4_filter-dd_filter_item_4_4" : ["826"],
        "4_filter-dd_filter_item_5" : ["1"],
        "4_filter-dd_filter_item_6" : ["1"],
        "4_filter-dd_filter_item_7_1" : [],
        "4_filter-dd_filter_item_7_2" : ["36"],
        "4_filter-dd_filter_item_8" : ["10"],
        "4_filter-dd_filter_item_9" : ["1"],
        "4_filter-dd_filter_item_10" : ["1"],
        "4_filter-dd_filter_item_11" : ["1", "2", "3"],

        //15= indicator id
        "5_filter-dd_filter_item_1" :  [],
        "5_filter-dd_filter_item_2" : ["1"],
        "5_filter-dd_filter_item_3" : ["1"],
        "5_filter-dd_filter_item_4_1" : [],
        "5_filter-dd_filter_item_4_2" : [],
        "5_filter-dd_filter_item_4_3" : ["744"],
        "5_filter-dd_filter_item_4_4" : ["826"],
        "5_filter-dd_filter_item_5" : ["1"],
        "5_filter-dd_filter_item_6" : ["1"],
        "5_filter-dd_filter_item_7_1" : [],
        "5_filter-dd_filter_item_7_2" : ["36"],
        "5_filter-dd_filter_item_8" : ["15"],
        "5_filter-dd_filter_item_9" : ["1"],
        "5_filter-dd_filter_item_10" : [],
        "5_filter-dd_filter_item_11" : ["1"],
        "5_filter-dd_filter_item_12" : ["1", "2", "3"],

        //14= indicator id
        "6_filter-dd_filter_item_1" :  [],
        "6_filter-dd_filter_item_2" : ["1"],
        "6_filter-dd_filter_item_3" : ["1"],
        "6_filter-dd_filter_item_4_1" : [],
        "6_filter-dd_filter_item_4_2" : [],
        "6_filter-dd_filter_item_4_3" : ["744"],
        "6_filter-dd_filter_item_4_4" : ["826"],
        "6_filter-dd_filter_item_5" : ["1"],
        "6_filter-dd_filter_item_6" : ["1"],
        "6_filter-dd_filter_item_7_1" : [],
        "6_filter-dd_filter_item_7_2" : ["36"],
        "6_filter-dd_filter_item_8" : ["14"],
        "6_filter-dd_filter_item_9" : ["1"],
        "6_filter-dd_filter_item_10" : [],
        "6_filter-dd_filter_item_11" : ["1"],
        "6_filter-dd_filter_item_12" : ["1", "2", "3"],

        //22= indicator id
        "22_filter-dd_filter_item_1" :  [],
        "22_filter-dd_filter_item_2" : ["1"],
        "22_filter-dd_filter_item_3" : [],
        "22_filter-dd_filter_item_4_1" : [],
        "22_filter-dd_filter_item_4_2" : [],
        "22_filter-dd_filter_item_4_3" : ["744"],
        "22_filter-dd_filter_item_4_4" : ["826"],
        "22_filter-dd_filter_item_5" : ["1"],
        "22_filter-dd_filter_item_6" : ["1"],
        "22_filter-dd_filter_item_7_1" : [],
        "22_filter-dd_filter_item_7_2" : ["36"],
        "22_filter-dd_filter_item_8" : ["22"],
        "22_filter-dd_filter_item_9" : ["1"],
        "22_filter-dd_filter_item_10" : [],
        "22_filter-dd_filter_item_11" : ["1"],
        "22_filter-dd_filter_item_12" : ["1", "2", "3"],


        //24= indicator id
        "8_filter-dd_filter_item_1" :  [],
        "8_filter-dd_filter_item_2" : ["1"],
        "8_filter-dd_filter_item_3" : ["1"],
        "8_filter-dd_filter_item_4_1" : [],
        "8_filter-dd_filter_item_4_2" : [],
        "8_filter-dd_filter_item_4_3" : ["744"],
        "8_filter-dd_filter_item_4_4" : ["826"],
        "8_filter-dd_filter_item_5" : ["1"],
        "8_filter-dd_filter_item_6" : ["1"],
        "8_filter-dd_filter_item_7_1" : [],
        "8_filter-dd_filter_item_7_2" : ["36"],
        "8_filter-dd_filter_item_8" : ["24"],
        "8_filter-dd_filter_item_9" : ["1"],
        "8_filter-dd_filter_item_10" : [],
        "8_filter-dd_filter_item_11" : ["1"],
        "8_filter-dd_filter_item_12" : ["1", "2", "3"],


        //28= indicator id
        "9_filter-dd_filter_item_1" :  [],
        "9_filter-dd_filter_item_2" : ["1"],
        "9_filter-dd_filter_item_3" : ["1"],
        "9_filter-dd_filter_item_4_1" : [],
        "9_filter-dd_filter_item_4_2" : [],
        "9_filter-dd_filter_item_4_3" : ["744"],
        "9_filter-dd_filter_item_4_4" : ["826"],
        "9_filter-dd_filter_item_5" : ["1"],
        "9_filter-dd_filter_item_6" : ["1"],
        "9_filter-dd_filter_item_7_1" : [],
        "9_filter-dd_filter_item_7_2" : ["36"],
        "9_filter-dd_filter_item_8" : ["28"],
        "9_filter-dd_filter_item_9" : ["1"],
        "9_filter-dd_filter_item_10" : [],
        "9_filter-dd_filter_item_11" : ["1"],
        "9_filter-dd_filter_item_12" : ["1", "2", "3"],

        //28= indicator id
        "10_filter-dd_filter_item_1" :  [],
        "10_filter-dd_filter_item_2" : ["1"],
        "10_filter-dd_filter_item_3" : ["1"],
        "10_filter-dd_filter_item_4_1" : [],
        "10_filter-dd_filter_item_4_2" : [],
        "10_filter-dd_filter_item_4_3" : ["744"],
        "10_filter-dd_filter_item_4_4" : ["826"],
        "10_filter-dd_filter_item_5" : ["1"],
        "10_filter-dd_filter_item_6" : ["1"],
        "10_filter-dd_filter_item_7_1" : [],
        "10_filter-dd_filter_item_7_2" : ["36"],
        "10_filter-dd_filter_item_8" : ["16"],
        "10_filter-dd_filter_item_9" : ["1"],
        "10_filter-dd_filter_item_10" : [],
        "10_filter-dd_filter_item_11" : ["1"],
        "10_filter-dd_filter_item_12" : ["1", "2", "3"]

    };
});