define(function () {

    'use strict';

    return {

        "download_data": "DOWNLOAD DATA",
        "visualize_data": "VISUALIZE DATA",
        "domain_20": "Ex situ conservation",
        "activity1_20": "Germplasm collections -",
        "activity2_20": "Priority activity 6: Sustaining and expanding ex situ conservation of germplasm",
        "title_20": "Accessions conserved -",
        "indicator_20": "Indicator 20: Number of accessions conserved ex situ under medium or long-term conditions",
        "domain_2": "In situ conservation and management",
        "activity1_2": "Surveys and inventories -",
        "activity2_2": "Priority activity 1: Surveying and inventorying plant genetic resources for food and agriculture",
        "title_2": "Surveyed species/varieties",
        "indicator_2": "Indicator 2: Number of PGRFA surveyed/inventoried",
        "domain_10": "In situ conservation and management",
        "activity1_10": "Crop wild relatives and wild food plants -",
        "activity2_10": "Priority activity 4: Promoting in situ conservation and management of crop wild relatives and wild food plants",
        "title_10": "In situ conservation sites managing crop wild relatives and wild food plants -",
        "indicator_10": "Indicator 10: Percentage of national in situ conservation sites with management plans addressing crop wild relatives and wild food plants",
        "domain_3": "In situ conservation and management",
        "activity1_3": "Surveys and inventories -",
        "activity2_3": "Priority activity 1: Surveying and inventorying plant genetic resources for food and agriculture",
        "title_3": "Threatened species/varieties -",
        "indicator_3": "Indicator 3: Percentage of PGRFA surveyed/inventoried",
        "domain_15": "Ex situ conservation",
        "activity1_15": "Targeted collecting -",
        "activity2_15": "Priority activity 5: Supporting targeted collecting of plant genetic resources for food and agriculture",
        "title_15": "Targeted collecting missions",
        "indicator_15": "Indicator 15: Number of targeted collecting missions in the country",
        "domain_22": "Ex situ conservation",
        "activity1_22": "Regeneration of accessions -",
        "activity2_22": "Priority activity 7: Regenerating and multiplying ex situ accessions",
        "title_22": "Accessions at risk -",
        "indicator_22": "Indicator 22: Percentage of ex situ accessions in need of regeneration for which a budget for regeneration does not exist",
        "domain_14": "Ex situ conservation",
        "activity1_14": "Targeted collecting -",
        "activity2_14": "Priority activity 5: Supporting targeted collecting of plant genetic resources for food and agriculture",
        "title_14": "Crops requiring targeted collecting -",
        "indicator_14": "Indicator 14: Number of crops conserved in the national genebank(s) that require targeted collecting",
        "domain_28": "Sustainable use",
        "activity1_28": "Characterization and evaluation -",
        "activity2_28": "Priority activity 8: Expanding the characterization, evaluation and further development of specific collection subsets to facilitate use",
        "title_28": "Accessions distributed",
        "indicator_28": "Indicator 28: Number of accessions distributed by genebanks to users of germplasm",
        "domain_29": "Sustainable use",
        "activity1_29": "Characterization and evaluation -",
        "activity2_29": "Priority activity 8: Expanding the characterization, evaluation and further development of specific collection subsets to facilitate use",
        "title_29": "Samples distributed",
        "indicator_29": "Indicator 29: Number of samples distributed by genebanks to users of germplasm",
        "domain_16": "Ex situ conservation",
        "activity1_16": "Targeted collecting -",
        "activity2_16": "Priority activity 5: Supporting targeted collecting of plant genetic resources for food and agriculture",
        "title_16": "Samples collected",
        "indicator_16": "Indicator 16: Number of accessions resulting from targeted collecting missions in the country",

        "loading_in_progress": "Loading in progress",
        "completed": "Completed",
        "filter-vd_filter_button_1_title": "Show",
        "filter-dd_filter_button_1_title": "Show Data",
        "filter-dd_filter_button_title": "Download Data",
        "filter-dd_filter_button_2_title": "Table Data",
        "filter-dd_filter_button_3_title": "Raw Data",
        "download_in_progress": "Your download request has been sent. Please wait.",
        "download_toomuch" : "Too many records please refine your query.<br>The maximum limit is 200,000 records",
        "download_in_error": "Error occurred during resource export. Please contact support.",

        // Indicator 20
        "1_vd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for each selector.",
        "1_vd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "1_filter-vd_filter_item_1_title": "COUNTRIES",
        "1_filter-vd_filter_item_4_1_title": "REGIONS",
        "1_filter-vd_filter_item_7_title": "SPECIAL GROUPS",
        "1_filter-vd_filter_item_8_title": "GENUS",
        "1_filter-vd_filter_item_9_title": "PERIODS",
        "1_filter-vd_filter_item_2_choicesTitle1": "FAO",
        "1_filter-vd_filter_item_2_choicesTitle2": "M49",
        "1_filter-vd_filter_item_2_choicesTitle3": "SDG",
        "1_filter-vd_filter_item_2_choicesTitle4": "MDG",
        "1_filter-vd_filter_item_3_choicesTitle1": "Total",
        "1_filter-vd_filter_item_3_choicesTitle2": "List of country",
        "1_filter-vd_filter_item_5_choicesTitle1": "CGRFA",
        "1_filter-vd_filter_item_5_choicesTitle2": "ITPGRFA",
        "1_filter-vd_filter_item_6_choicesTitle1": "Total",
        "1_filter-vd_filter_item_6_choicesTitle2": "List of country",

        "1_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "1_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "1_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "1_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "1_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "1_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "1_filter-dd_filter_item_1_title": "COUNTRIES",
        "1_filter-dd_filter_item_4_1_title": "REGIONS",
        "1_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "1_filter-dd_filter_item_8_title": "ELEMENTS",
        "1_filter-dd_filter_item_9_title": "PERIODS",
        "1_filter-dd_filter_item_10_title": "INCLUDE STAKEHOLDERS",
        "1_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "1_filter-dd_filter_item_2_choicesTitle2": "M49",
        "1_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "1_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "1_filter-dd_filter_item_3_choicesTitle1": "Total",
        "1_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "1_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "1_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "1_filter-dd_filter_item_6_choicesTitle1": "Total",
        "1_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "1_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "1_filter-dd_filter_item_12_title": "Output Formatting Options",
        "1_filter-dd_filter_item_11_choicesTitle1": "None",
        "1_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "1_filter-dd_filter_item_11_choicesTitle3": "Period",
        "1_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "1_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "1_filter-dd_filter_item_12_choicesTitle3": "Units",
        "1_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "1_filter-dd_filter_item_10_source1": "Stakeholders",
        "1_vd_dashboard_item_1_title": "Number of accessions conserved ex situ under medium or long-term conditions",
        "1_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",


        "1_vd_dashboard_item_2_title": "Biological status of the accessions",
        "1_vd_dashboard_item_3_title": "Accessions by country",
        "1_vd_dashboard_item_4_title": "Accessions by stakeholder",

        "1_vd_dashboard_item_1_uid": "Indicator20",
        "1_vd_dashboard_item_2_uid": "Indicator20",
        "1_vd_dashboard_item_3_uid": "Indicator20",
        "1_vd_dashboard_item_4_uid": "Indicator20",

        "1_dd_table_title_col_1": "Domain",
        "1_dd_table_title_col_2": "Country",
        "1_dd_table_title_col_3": "Element",
        "1_dd_table_title_col_4": "Indicator and Rating",
        "1_dd_table_title_col_5": "Period",
        "1_dd_table_title_col_6": "Value",

        // Indicator 2
        "2_vd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for each selector.",
        "2_vd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_filter-vd_filter_item_1_title": "COUNTRIES",
        "2_filter-vd_filter_item_4_1_title": "REGIONS",
        "2_filter-vd_filter_item_7_title": "SPECIAL GROUPS",
        "2_filter-vd_filter_item_8_title": "PERIODS",
        "2_filter-vd_filter_item_9_title": "FORMULA",
        "2_filter-vd_filter_item_2_choicesTitle1": "FAO",
        "2_filter-vd_filter_item_2_choicesTitle2": "M49",
        "2_filter-vd_filter_item_2_choicesTitle3": "SDG",
        "2_filter-vd_filter_item_2_choicesTitle4": "MDG",
        "2_filter-vd_filter_item_3_choicesTitle1": "Total",
        "2_filter-vd_filter_item_3_choicesTitle2": "List of country",
        "2_filter-vd_filter_item_5_choicesTitle1": "CGRFA",
        "2_filter-vd_filter_item_5_choicesTitle2": "ITPGRFA",
        "2_filter-vd_filter_item_6_choicesTitle1": "Total",
        "2_filter-vd_filter_item_6_choicesTitle2": "List of country",
        "2_filter-vd_filter_item_9_choicesTitle1": "Total",
        "2_filter-vd_filter_item_9_choicesTitle2": "Average",

        "2_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "2_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "2_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "2_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_filter-dd_filter_item_1_title": "COUNTRIES",
        "2_filter-dd_filter_item_4_1_title": "REGIONS",
        "2_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "2_filter-dd_filter_item_8_title": "ELEMENTS",
        "2_filter-dd_filter_item_9_title": "PERIODS",
        "2_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "2_filter-dd_filter_item_2_choicesTitle2": "M49",
        "2_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "2_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "2_filter-dd_filter_item_3_choicesTitle1": "Total",
        "2_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "2_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "2_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "2_filter-dd_filter_item_6_choicesTitle1": "Total",
        "2_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "2_filter-dd_filter_item_10_title": "Thousand Separator in 'Show Data'",
        "2_filter-dd_filter_item_11_title": "Output Formatting Options",
        "2_filter-dd_filter_item_10_choicesTitle1": "None",
        "2_filter-dd_filter_item_10_choicesTitle2": "Comma",
        "2_filter-dd_filter_item_10_choicesTitle3": "Period",
        "2_filter-dd_filter_item_11_choicesTitle1": "Flags",
        "2_filter-dd_filter_item_11_choicesTitle2": "Codes",
        "2_filter-dd_filter_item_11_choicesTitle3": "Units",
        "2_filter-dd_filter_item_11_choicesTitle4": "Null Values",

        "2_vd_dashboard_item_1_title": "Number of Varieties",
        "2_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",

        "2_vd_dashboard_item_2_title": "Number of Species",
        "2_vd_dashboard_item_3_title": "Species/varieties surveyed/inventoried by country",
        "2_vd_dashboard_item_4_title": "Species/varieties surveyed/inventoried by region",

        "2_vd_dashboard_item_3_series_yAxis_1_title": "Number of Varieties",
        "2_vd_dashboard_item_3_series_yAxis_2_title": "Number of Species",
        "2_vd_dashboard_item_4_series_yAxis_1_title": "Number of Varieties",
        "2_vd_dashboard_item_4_series_yAxis_2_title": "Number of Species",

        "2_vd_dashboard_item_1_uid": "Indicator2",
        "2_vd_dashboard_item_2_uid": "Indicator2",
        "2_vd_dashboard_item_3_uid": "Indicator2",
        "2_vd_dashboard_item_4_uid": "Indicator2",

        "2_dd_table_title_col_1": "Domain",
        "2_dd_table_title_col_2": "Country",
        "2_dd_table_title_col_3": "Element",
        "2_dd_table_title_col_4": "Indicator and Rating",
        "2_dd_table_title_col_5": "Period",
        "2_dd_table_title_col_6": "Value",



        // Indicator 3
        "3_vd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for each selector.",
        "3_vd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "3_filter-vd_filter_item_1_title": "COUNTRIES",
        "3_filter-vd_filter_item_4_1_title": "REGIONS",
        "3_filter-vd_filter_item_7_title": "SPECIAL GROUPS",
        "3_filter-vd_filter_item_8_title": "PERIODS",
        "3_filter-vd_filter_item_2_choicesTitle1": "FAO",
        "3_filter-vd_filter_item_2_choicesTitle2": "M49",
        "3_filter-vd_filter_item_2_choicesTitle3": "SDG",
        "3_filter-vd_filter_item_2_choicesTitle4": "MDG",
        "3_filter-vd_filter_item_3_choicesTitle1": "Total",
        "3_filter-vd_filter_item_3_choicesTitle2": "List of country",
        "3_filter-vd_filter_item_5_choicesTitle1": "CGRFA",
        "3_filter-vd_filter_item_5_choicesTitle2": "ITPGRFA",
        "3_filter-vd_filter_item_6_choicesTitle1": "Total",
        "3_filter-vd_filter_item_6_choicesTitle2": "List of country",
        "3_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "3_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "3_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "3_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "3_filter-dd_filter_item_1_title": "COUNTRIES",
        "3_filter-dd_filter_item_4_1_title": "REGIONS",
        "3_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "3_filter-dd_filter_item_8_title": "ELEMENTS",
        "3_filter-dd_filter_item_9_title": "PERIODS",
        "3_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "3_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "3_filter-dd_filter_item_2_choicesTitle2": "M49",
        "3_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "3_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "3_filter-dd_filter_item_3_choicesTitle1": "Total",
        "3_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "3_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "3_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "3_filter-dd_filter_item_6_choicesTitle1": "Total",
        "3_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "3_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "3_filter-dd_filter_item_12_title": "Output Formatting Options",
        "3_filter-dd_filter_item_11_choicesTitle1": "None",
        "3_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "3_filter-dd_filter_item_11_choicesTitle3": "Period",
        "3_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "3_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "3_filter-dd_filter_item_12_choicesTitle3": "Units",
        "3_filter-dd_filter_item_12_choicesTitle4": "Null Values",
        "3_filter-dd_filter_item_8_source1": "Percentage of species threatened out of those surveyed/inventoried",
        "3_filter-dd_filter_item_8_source2": "Percentage of varieties threatened out of those surveyed/inventoried",
        "3_filter-dd_filter_item_10_source1": "Stakeholders",
        "3_vd_dashboard_item_1_title": "Percentage of species surveyed/inventoried",
        "3_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",
        "3_vd_dashboard_item_2_title": "Percentage of varieties surveyed/inventoried",
        "3_vd_dashboard_item_3_title": "Status of species surveyed/inventoried by region",
        "3_vd_dashboard_item_4_title": "Status of varieties surveyed/inventoried by region",
        "3_vd_dashboard_item_5_title": "Percentage of species surveyed/inventoried by status, global",
        "3_vd_dashboard_item_6_title": "Percentage of varieties surveyed/inventoried by status, global",
        "3_vd_dashboard_item_1_uid": "Indicator3",
        "3_vd_dashboard_item_2_uid": "Indicator3",
        "3_vd_dashboard_item_3_uid": "Indicator3",
        "3_vd_dashboard_item_4_uid": "Indicator3",
        "3_vd_dashboard_item_5_uid": "Indicator3",
        "3_vd_dashboard_item_6_uid": "Indicator3",
        "3_dd_table_title_col_1": "Domain",
        "3_dd_table_title_col_2": "Country",
        "3_dd_table_title_col_3": "Element",
        "3_dd_table_title_col_4": "Indicator and Rating",
        "3_dd_table_title_col_5": "Period",
        "3_dd_table_title_col_6": "Percentage",


        "4_vd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for each selector.",
        "4_vd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "4_filter-vd_filter_item_1_title": "COUNTRIES",
        "4_filter-vd_filter_item_4_1_title": "REGIONS",
        "4_filter-vd_filter_item_7_title": "SPECIAL GROUPS",
        "4_filter-vd_filter_item_8_title": "PERIODS",
        "4_filter-vd_filter_item_2_choicesTitle1": "FAO",
        "4_filter-vd_filter_item_2_choicesTitle2": "M49",
        "4_filter-vd_filter_item_2_choicesTitle3": "SDG",
        "4_filter-vd_filter_item_2_choicesTitle4": "MDG",
        "4_filter-vd_filter_item_3_choicesTitle1": "Total",
        "4_filter-vd_filter_item_3_choicesTitle2": "List of country",
        "4_filter-vd_filter_item_5_choicesTitle1": "CGRFA",
        "4_filter-vd_filter_item_5_choicesTitle2": "ITPGRFA",
        "4_filter-vd_filter_item_6_choicesTitle1": "Total",
        "4_filter-vd_filter_item_6_choicesTitle2": "List of country",
        "4_filter-vd_filter_item_9_choicesTitle1": "Total",
        "4_filter-vd_filter_item_9_choicesTitle2": "Average",

        "4_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "4_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "4_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "4_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "4_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "4_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "4_filter-dd_filter_item_1_title": "COUNTRIES",
        "4_filter-dd_filter_item_4_1_title": "REGIONS",
        "4_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "4_filter-dd_filter_item_8_title": "ELEMENTS",
        "4_filter-dd_filter_item_9_title": "PERIODS",
        "4_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "4_filter-dd_filter_item_2_choicesTitle2": "M49",
        "4_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "4_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "4_filter-dd_filter_item_3_choicesTitle1": "Total",
        "4_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "4_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "4_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "4_filter-dd_filter_item_6_choicesTitle1": "Total",
        "4_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "4_filter-dd_filter_item_10_title": "Thousand Separator in 'Show Data'",
        "4_filter-dd_filter_item_11_title": "Output Formatting Options",
        "4_filter-dd_filter_item_10_choicesTitle1": "None",
        "4_filter-dd_filter_item_10_choicesTitle2": "Comma",
        "4_filter-dd_filter_item_10_choicesTitle3": "Period",
        "4_filter-dd_filter_item_11_choicesTitle1": "Flags",
        "4_filter-dd_filter_item_11_choicesTitle2": "Codes",
        "4_filter-dd_filter_item_11_choicesTitle3": "Units",
        "4_filter-dd_filter_item_11_choicesTitle4": "Null Values",

        "4_vd_dashboard_item_1_title": "Percentage of national in situ conservation sites with management plans addressing crop wild relatives and wild food plants",
        "4_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",

        "4_vd_dashboard_item_2_title": "In situ conservation sites managing crop wild relatives and wild food plants",

        "4_vd_dashboard_item_1_uid": "Indicator10",
        "4_vd_dashboard_item_2_uid": "Indicator10",
        "4_vd_dashboard_item_3_uid": "Indicator10",
        "4_vd_dashboard_item_4_uid": "Indicator10",

        "4_dd_table_title_col_1": "Domain",
        "4_dd_table_title_col_2": "Country",
        "4_dd_table_title_col_3": "Element",
        "4_dd_table_title_col_4": "Indicator and Rating",
        "4_dd_table_title_col_5": "Period",
        "4_dd_table_title_col_6": "Value",


        // Indicator 15

        "5_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "5_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "5_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "5_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "5_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "5_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "5_filter-dd_filter_item_1_title": "COUNTRIES",
        "5_filter-dd_filter_item_4_1_title": "REGIONS",
        "5_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "5_filter-dd_filter_item_8_title": "ELEMENTS",
        "5_filter-dd_filter_item_9_title": "PERIODS",
        "5_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "5_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "5_filter-dd_filter_item_2_choicesTitle2": "M49",
        "5_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "5_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "5_filter-dd_filter_item_3_choicesTitle1": "Total",
        "5_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "5_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "5_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "5_filter-dd_filter_item_6_choicesTitle1": "Total",
        "5_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "5_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "5_filter-dd_filter_item_12_title": "Output Formatting Options",
        "5_filter-dd_filter_item_11_choicesTitle1": "None",
        "5_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "5_filter-dd_filter_item_11_choicesTitle3": "Period",
        "5_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "5_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "5_filter-dd_filter_item_12_choicesTitle3": "Units",
        "5_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "5_filter-dd_filter_item_10_source1": "Stakeholders",

        "5_dd_table_title_col_1": "Domain",
        "5_dd_table_title_col_2": "Country",
        "5_dd_table_title_col_3": "Element",
        "5_dd_table_title_col_4": "Indicator and Rating",
        "5_dd_table_title_col_5": "Period",
        "5_dd_table_title_col_6": "Value",

        // Indicator 22

        "7_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "7_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "7_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "7_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "7_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "7_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "7_filter-dd_filter_item_1_title": "COUNTRIES",
        "7_filter-dd_filter_item_4_1_title": "REGIONS",
        "7_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "7_filter-dd_filter_item_8_title": "ELEMENTS",
        "7_filter-dd_filter_item_9_title": "PERIODS",
        "7_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "7_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "7_filter-dd_filter_item_2_choicesTitle2": "M49",
        "7_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "7_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "7_filter-dd_filter_item_3_choicesTitle1": "Total",
        "7_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "7_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "7_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "7_filter-dd_filter_item_6_choicesTitle1": "Total",
        "7_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "7_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "7_filter-dd_filter_item_12_title": "Output Formatting Options",
        "7_filter-dd_filter_item_11_choicesTitle1": "None",
        "7_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "7_filter-dd_filter_item_11_choicesTitle3": "Period",
        "7_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "7_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "7_filter-dd_filter_item_12_choicesTitle3": "Units",
        "7_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "7_filter-dd_filter_item_10_source1": "Stakeholders",

        "7_dd_table_title_col_1": "Domain",
        "7_dd_table_title_col_2": "Country",
        "7_dd_table_title_col_3": "Element",
        "7_dd_table_title_col_4": "Indicator and Rating",
        "7_dd_table_title_col_5": "Period",
        "7_dd_table_title_col_6": "Value",

        // Indicator 14
        "6_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "6_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "6_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "6_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "6_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "6_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "6_filter-dd_filter_item_1_title": "COUNTRIES",
        "6_filter-dd_filter_item_4_1_title": "REGIONS",
        "6_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "6_filter-dd_filter_item_8_title": "ELEMENTS",
        "6_filter-dd_filter_item_9_title": "PERIODS",
        "6_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "6_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "6_filter-dd_filter_item_2_choicesTitle2": "M49",
        "6_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "6_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "6_filter-dd_filter_item_3_choicesTitle1": "Total",
        "6_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "6_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "6_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "6_filter-dd_filter_item_6_choicesTitle1": "Total",
        "6_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "6_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "6_filter-dd_filter_item_12_title": "Output Formatting Options",
        "6_filter-dd_filter_item_11_choicesTitle1": "None",
        "6_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "6_filter-dd_filter_item_11_choicesTitle3": "Period",
        "6_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "6_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "6_filter-dd_filter_item_12_choicesTitle3": "Units",
        "6_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "6_filter-dd_filter_item_10_source1": "Stakeholders",

        "6_dd_table_title_col_1": "Domain",
        "6_dd_table_title_col_2": "Country",
        "6_dd_table_title_col_3": "Element",
        "6_dd_table_title_col_4": "Indicator and Rating",
        "6_dd_table_title_col_5": "Period",
        "6_dd_table_title_col_6": "Value",

        // Indicator 24

        "8_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "8_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "8_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "8_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "8_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "8_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "8_filter-dd_filter_item_1_title": "COUNTRIES",
        "8_filter-dd_filter_item_4_1_title": "REGIONS",
        "8_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "8_filter-dd_filter_item_8_title": "ELEMENTS",
        "8_filter-dd_filter_item_9_title": "PERIODS",
        "8_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "8_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "8_filter-dd_filter_item_2_choicesTitle2": "M49",
        "8_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "8_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "8_filter-dd_filter_item_3_choicesTitle1": "Total",
        "8_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "8_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "8_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "8_filter-dd_filter_item_6_choicesTitle1": "Total",
        "8_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "8_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "8_filter-dd_filter_item_12_title": "Output Formatting Options",
        "8_filter-dd_filter_item_11_choicesTitle1": "None",
        "8_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "8_filter-dd_filter_item_11_choicesTitle3": "Period",
        "8_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "8_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "8_filter-dd_filter_item_12_choicesTitle3": "Units",
        "8_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "8_filter-dd_filter_item_10_source1": "Stakeholders",

        "8_dd_table_title_col_1": "Domain",
        "8_dd_table_title_col_2": "Country",
        "8_dd_table_title_col_3": "Element",
        "8_dd_table_title_col_4": "Indicator and Rating",
        "8_dd_table_title_col_5": "Period",
        "8_dd_table_title_col_6": "Value",

        // Indicator 15

        "9_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "9_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "9_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "9_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "9_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "9_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "9_filter-dd_filter_item_1_title": "COUNTRIES",
        "9_filter-dd_filter_item_4_1_title": "REGIONS",
        "9_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "9_filter-dd_filter_item_8_title": "ELEMENTS",
        "9_filter-dd_filter_item_9_title": "PERIODS",
        "9_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "9_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "9_filter-dd_filter_item_2_choicesTitle2": "M49",
        "9_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "9_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "9_filter-dd_filter_item_3_choicesTitle1": "Total",
        "9_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "9_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "9_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "9_filter-dd_filter_item_6_choicesTitle1": "Total",
        "9_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "9_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "9_filter-dd_filter_item_12_title": "Output Formatting Options",
        "9_filter-dd_filter_item_11_choicesTitle1": "None",
        "9_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "9_filter-dd_filter_item_11_choicesTitle3": "Period",
        "9_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "9_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "9_filter-dd_filter_item_12_choicesTitle3": "Units",
        "9_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "9_filter-dd_filter_item_10_source1": "Stakeholders",

        "9_dd_table_title_col_1": "Domain",
        "9_dd_table_title_col_2": "Country",
        "9_dd_table_title_col_3": "Element",
        "9_dd_table_title_col_4": "Indicator and Rating",
        "9_dd_table_title_col_5": "Period",
        "9_dd_table_title_col_6": "Value",

        // Indicator 16

        "10_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "10_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "10_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "10_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "10_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "10_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "10_filter-dd_filter_item_1_title": "COUNTRIES",
        "10_filter-dd_filter_item_4_1_title": "REGIONS",
        "10_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "10_filter-dd_filter_item_8_title": "ELEMENTS",
        "10_filter-dd_filter_item_9_title": "PERIODS",
        "10_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "10_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "10_filter-dd_filter_item_2_choicesTitle2": "M49",
        "10_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "10_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "10_filter-dd_filter_item_3_choicesTitle1": "Total",
        "10_filter-dd_filter_item_3_choicesTitle2": "List of country",
        "10_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "10_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "10_filter-dd_filter_item_6_choicesTitle1": "Total",
        "10_filter-dd_filter_item_6_choicesTitle2": "List of country",
        "10_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "10_filter-dd_filter_item_12_title": "Output Formatting Options",
        "10_filter-dd_filter_item_11_choicesTitle1": "None",
        "10_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "10_filter-dd_filter_item_11_choicesTitle3": "Period",
        "10_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "10_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "10_filter-dd_filter_item_12_choicesTitle3": "Units",
        "10_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "10_filter-dd_filter_item_10_source1": "Stakeholders",

        "10_dd_table_title_col_1": "Domain",
        "10_dd_table_title_col_2": "Country",
        "10_dd_table_title_col_3": "Element",
        "10_dd_table_title_col_4": "Indicator and Rating",
        "10_dd_table_title_col_5": "Period",
        "10_dd_table_title_col_6": "Value",

        "10_filter-vd_filter_item_8_title": "PERIODS",

        "10_vd_dashboard_item_1_title": "Total Number of Samples",
        "10_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",
        "10_vd_dashboard_item_2_title": "Average Number of Samples",
        "10_vd_dashboard_item_2_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",
        "10_vd_dashboard_item_3_title": "Collected samples by region",
        "10_vd_dashboard_item_4_title": "Collected samples by country",

        // Organizations

        "search_advanced": "Hide Advanced",
        "search_basic": "Show Advanced",
        "organizations_button_backtosearch": "Back to Search",
        "organizations_button_backtoresults": "Back to Results",
        "organizations_button_backtosearch_fromomni": "Back to Search",
        "organizations_search_not_found": "No matching records found.",
        "organizations_search_filter" : "Filter",
        "organizations_search_orgalert_message" : "Please provide a valid search",
        "organizations_search_from_querystring" : "Instcode not found. Please use the search form.",
        "organizations_omnisearch_placeholder": "Type here your search by Name, Organization acronym, WIEWS instcode, City or Country",
        "organizations_search_header": "Search",
        "organizations_results_header": "Results",
        "organizations_details_header": "Details",
        "organizations_search_showadvanced": "Show Advanced",
        "organizations_searchform_search_name": "Name of organization",
        "organizations_searchform_search_organization": "Organization acronym",
        "organizations_searchform_search_instcode": "WIEWS instcode",
        "organizations_searchform_search_city": "City",
        "organizations_searchform_search_country": "Country",
        "organizations_searchform_search_organizationrole" : "Organization role categories",
        "organizations_searchform_search_validation" : "Valid/invalidated organizations",
        "organizations_searchform_search_validation_true" : "Valid only",
        "organizations_searchform_search_validation_null" : "Valid and invalidated",
        "organizations_searchform_search_validation_false" : "Invalidated only",
        "organizations_table_header_name" : "Name",
        "organizations_table_header_acronym" : "Acronym",
        "organizations_table_header_instcode" : "WIEWS instcode",
        "organizations_table_header_parentorg" : "Parent organization",
        "organizations_table_header_address" : "Address",
        "organizations_table_header_city" : "City",
        "organizations_table_header_country" : "Country",
        "organizations_details_invalidheader" : "This record is invalid.",
        "organizations_export_button_alt" : "Export this result",

        // Ex Situ Map

        "exsitu_holdings_footnote" : "This map currently shows Institution with georeferencing data only.",

        // Ex Situ Search
        "exsitu_search_header": "Search for ",
        "exsitu_search_showadvanced": "Hide Advanced",
        "exsitu-search_omnisearch_placeholder" :  "Type here your search",
        "exsitu-search_search_instcode" :  "Holding institute code",
        "exsitu-search_search_accessions" :  "Accession number",
        "exsitu-search_search_genus" :  "Name of genus",
        "exsitu-search_search_spieces" :  "Name of species",
        "exsitu-search_search_crop" :  "Name of crop",
        "exsitu-search_search_country_origin" :  "Country of origin",
        "exsitu-search_search_country_institute" :  "Country",
        "exsitu-search_search_year" :  "Reporting year",
        "exsitu-search_search_taxon" :  "Name of taxon",
        "exsitu-search_search_statusofaccession" :  "Biological status of accession",
        "exsitu-search_search_statusmultilateral" :  "Status under the Multilateral System",

        "exsitu-search_search_statusmultilateral_true" : "Included",
        "exsitu-search_search_statusmultilateral_false" : "Not Included",

        // Other stuff

        "bootstraptable_search_filter" : "Filter"
    }
});