define(function () {

    'use strict';

    return {


        "download_data": "DOWNLOAD DATA",
        "visualize_data": "VISUALIZE DATA",
        "20": "Indicator 20: Number of accessions conserved ex situ under medium or long-term conditions",
        "2": "Indicator 2: Number of PGRFA surveyed/inventoried",
        "3": "Indicator 3: Percentage of PGRFA surveyed/inventoried",

        "loading_in_progress": "Loading in progress",
        "completed": "Completed",
        "filter-vd_filter_button_1_title": "Show",
        "filter-dd_filter_button_1_title": "Show Data",
        "filter-dd_filter_button_title": "Download Data",
        "filter-dd_filter_button_2_title": "Table Data",
        "filter-dd_filter_button_3_title": "Raw Data",

        // Indicator 20
        "1_vd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for each selector.",
        "1_vd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "1_filter-vd_filter_item_1_title": "COUNTRIES",
        "1_filter-vd_filter_item_4_1_title": "REGIONS",
        "1_filter-vd_filter_item_7_title": "SPECIAL GROUPS",
        "1_filter-vd_filter_item_8_title": "GENUS",
        "1_filter-vd_filter_item_9_title": "PERIODS",
        "1_filter-vd_filter_item_2_choicesTitle1": "FAO",
        "1_filter-vd_filter_item_2_choicesTitle2": "M49",
        "1_filter-vd_filter_item_2_choicesTitle3": "SDG",
        "1_filter-vd_filter_item_2_choicesTitle4": "MDG",
        "1_filter-vd_filter_item_3_choicesTitle1": "Total",
        "1_filter-vd_filter_item_3_choicesTitle2": "List",
        "1_filter-vd_filter_item_5_choicesTitle1": "CGRFA",
        "1_filter-vd_filter_item_5_choicesTitle2": "ITPGRFA",
        "1_filter-vd_filter_item_6_choicesTitle1": "Total",
        "1_filter-vd_filter_item_6_choicesTitle2": "List",

        "1_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "1_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "1_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "1_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "1_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "1_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",

        "1_filter-dd_filter_item_1_title": "COUNTRIES",
        "1_filter-dd_filter_item_4_1_title": "REGIONS",
        "1_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "1_filter-dd_filter_item_8_title": "ELEMENTS",
        "1_filter-dd_filter_item_9_title": "PERIODS",
        "1_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "1_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "1_filter-dd_filter_item_2_choicesTitle2": "M49",
        "1_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "1_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "1_filter-dd_filter_item_3_choicesTitle1": "Total",
        "1_filter-dd_filter_item_3_choicesTitle2": "List",
        "1_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "1_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "1_filter-dd_filter_item_6_choicesTitle1": "Total",
        "1_filter-dd_filter_item_6_choicesTitle2": "List",
        "1_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "1_filter-dd_filter_item_12_title": "Output Formatting Options",
        "1_filter-dd_filter_item_11_choicesTitle1": "None",
        "1_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "1_filter-dd_filter_item_11_choicesTitle3": "Period",
        "1_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "1_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "1_filter-dd_filter_item_12_choicesTitle3": "Units",
        "1_filter-dd_filter_item_12_choicesTitle4": "Null Values",

        "1_filter-dd_filter_item_8_source1": "Number of accessions conserved ex situ under medium or long-term conditions",
        "1_filter-dd_filter_item_10_source1": "Stakeholders",
        "1_vd_dashboard_item_1_title": "Map title to be placed here",
        "1_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",


        "1_vd_dashboard_item_2_title": "Chart title to be placed here",
        "1_vd_dashboard_item_3_title": "Accessions by country",
        "1_vd_dashboard_item_4_title": "Accessions by stakeholder",


        "1_vd_dashboard_item_1_uid": "Indicator20",
        "1_vd_dashboard_item_2_uid": "Indicator20",
        "1_vd_dashboard_item_3_uid": "Indicator20",
        "1_vd_dashboard_item_4_uid": "Indicator20",



        "1_dd_table_title_col_1": "Domain",
        "1_dd_table_title_col_2": "Country",
        "1_dd_table_title_col_3": "Element",
        "1_dd_table_title_col_4": "Indicator and Rating",
        "1_dd_table_title_col_5": "Period",
        "1_dd_table_title_col_6": "Value",


        "2_vd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for each selector.",
        "2_vd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_filter-vd_filter_item_1_title": "COUNTRIES",
        "2_filter-vd_filter_item_4_1_title": "REGIONS",
        "2_filter-vd_filter_item_7_title": "SPECIAL GROUPS",
        "2_filter-vd_filter_item_8_title": "PERIODS",
        "2_filter-vd_filter_item_9_title": "FORMULA",
        "2_filter-vd_filter_item_2_choicesTitle1": "FAO",
        "2_filter-vd_filter_item_2_choicesTitle2": "M49",
        "2_filter-vd_filter_item_2_choicesTitle3": "SDG",
        "2_filter-vd_filter_item_2_choicesTitle4": "MDG",
        "2_filter-vd_filter_item_3_choicesTitle1": "Total",
        "2_filter-vd_filter_item_3_choicesTitle2": "List",
        "2_filter-vd_filter_item_5_choicesTitle1": "CGRFA",
        "2_filter-vd_filter_item_5_choicesTitle2": "ITPGRFA",
        "2_filter-vd_filter_item_6_choicesTitle1": "Total",
        "2_filter-vd_filter_item_6_choicesTitle2": "List",
        "2_filter-vd_filter_item_9_choicesTitle1": "Average",

        "2_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "2_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "2_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_dd_filter_button_3_msg": "The selection is not valid. Please, select at least an item for the geographical selector and at least an item for the period selector.",
        "2_dd_filter_button_3_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "2_filter-dd_filter_item_1_title": "COUNTRIES",
        "2_filter-dd_filter_item_4_1_title": "REGIONS",
        "2_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "2_filter-dd_filter_item_8_title": "ELEMENTS",
        "2_filter-dd_filter_item_9_title": "PERIODS",
        "2_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "2_filter-dd_filter_item_2_choicesTitle2": "M49",
        "2_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "2_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "2_filter-dd_filter_item_3_choicesTitle1": "Total",
        "2_filter-dd_filter_item_3_choicesTitle2": "List",
        "2_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "2_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "2_filter-dd_filter_item_6_choicesTitle1": "Total",
        "2_filter-dd_filter_item_6_choicesTitle2": "List",
        "2_filter-dd_filter_item_10_title": "Thousand Separator in 'Show Data'",
        "2_filter-dd_filter_item_11_title": "Output Formatting Options",
        "2_filter-dd_filter_item_10_choicesTitle1": "None",
        "2_filter-dd_filter_item_10_choicesTitle2": "Comma",
        "2_filter-dd_filter_item_10_choicesTitle3": "Period",
        "2_filter-dd_filter_item_11_choicesTitle1": "Flags",
        "2_filter-dd_filter_item_11_choicesTitle2": "Codes",
        "2_filter-dd_filter_item_11_choicesTitle3": "Units",
        "2_filter-dd_filter_item_11_choicesTitle4": "Null Values",

        "2_filter-dd_filter_item_8_source1": "Number of accessions conserved ex situ under medium or long-term conditions",
        "2_vd_dashboard_item_1_title": "Map title to be placed here",
        "2_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",

        "2_vd_dashboard_item_2_title": "Map title to be placed here",
        "2_vd_dashboard_item_3_title": "Chart title to be placed here",
        "2_vd_dashboard_item_4_title": "Chart title to be placed here",

        "2_vd_dashboard_item_3_series_yAxis_1_title": "Number of Varieties",
        "2_vd_dashboard_item_3_series_yAxis_2_title": "Number of Species",
        "2_vd_dashboard_item_4_series_yAxis_1_title": "Number of Varieties",
        "2_vd_dashboard_item_4_series_yAxis_2_title": "Number of Species",

        "2_vd_dashboard_item_1_uid": "Indicator2",
        "2_vd_dashboard_item_2_uid": "Indicator2",
        "2_vd_dashboard_item_3_uid": "Indicator2",
        "2_vd_dashboard_item_4_uid": "Indicator2",

        "2_dd_table_title_col_1": "Domain",
        "2_dd_table_title_col_2": "Country",
        "2_dd_table_title_col_3": "Element",
        "2_dd_table_title_col_4": "Indicator and Rating",
        "2_dd_table_title_col_5": "Period",
        "2_dd_table_title_col_6": "Value",



        // Indicator 3
        "3_vd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for each selector.",
        "3_vd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "3_filter-vd_filter_item_1_title": "COUNTRIES",
        "3_filter-vd_filter_item_4_1_title": "REGIONS",
        "3_filter-vd_filter_item_7_title": "SPECIAL GROUPS",
        "3_filter-vd_filter_item_8_title": "GENUS",
        "3_filter-vd_filter_item_9_title": "PERIODS",
        "3_filter-vd_filter_item_2_choicesTitle1": "FAO",
        "3_filter-vd_filter_item_2_choicesTitle2": "M49",
        "3_filter-vd_filter_item_2_choicesTitle3": "SDG",
        "3_filter-vd_filter_item_2_choicesTitle4": "MDG",
        "3_filter-vd_filter_item_3_choicesTitle1": "Total",
        "3_filter-vd_filter_item_3_choicesTitle2": "List",
        "3_filter-vd_filter_item_5_choicesTitle1": "CGRFA",
        "3_filter-vd_filter_item_5_choicesTitle2": "ITPGRFA",
        "3_filter-vd_filter_item_6_choicesTitle1": "Total",
        "3_filter-vd_filter_item_6_choicesTitle2": "List",
        "3_dd_filter_button_1_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "3_dd_filter_button_1_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "3_dd_filter_button_2_msg": "The selection is not valid. Please, select at least an item for the geographical selector, at least an item for the elements selector and at least an item for the period selector.",
        "3_dd_filter_button_2_list_msg": "The selection is not valid. Please, select list or total in the geographical selector.",
        "3_filter-dd_filter_item_1_title": "COUNTRIES",
        "3_filter-dd_filter_item_4_1_title": "REGIONS",
        "3_filter-dd_filter_item_7_title": "SPECIAL GROUPS",
        "3_filter-dd_filter_item_8_title": "ELEMENTS",
        "3_filter-dd_filter_item_9_title": "PERIODS",
        "3_filter-dd_filter_item_10_title": "STAKEHOLDERS",
        "3_filter-dd_filter_item_2_choicesTitle1": "FAO",
        "3_filter-dd_filter_item_2_choicesTitle2": "M49",
        "3_filter-dd_filter_item_2_choicesTitle3": "SDG",
        "3_filter-dd_filter_item_2_choicesTitle4": "MDG",
        "3_filter-dd_filter_item_3_choicesTitle1": "Total",
        "3_filter-dd_filter_item_3_choicesTitle2": "List",
        "3_filter-dd_filter_item_5_choicesTitle1": "CGRFA",
        "3_filter-dd_filter_item_5_choicesTitle2": "ITPGRFA",
        "3_filter-dd_filter_item_6_choicesTitle1": "Total",
        "3_filter-dd_filter_item_6_choicesTitle2": "List",
        "3_filter-dd_filter_item_11_title": "Thousand Separator in 'Show Data'",
        "3_filter-dd_filter_item_12_title": "Output Formatting Options",
        "3_filter-dd_filter_item_11_choicesTitle1": "None",
        "3_filter-dd_filter_item_11_choicesTitle2": "Comma",
        "3_filter-dd_filter_item_11_choicesTitle3": "Period",
        "3_filter-dd_filter_item_12_choicesTitle1": "Flags",
        "3_filter-dd_filter_item_12_choicesTitle2": "Codes",
        "3_filter-dd_filter_item_12_choicesTitle3": "Units",
        "3_filter-dd_filter_item_12_choicesTitle4": "Null Values",
        "3_filter-dd_filter_item_8_source1": "Percentage of species threatened out of those surveyed/inventoried",
        "3_filter-dd_filter_item_8_source2": "Percentage of varieties threatened out of those surveyed/inventoried",
        "3_filter-dd_filter_item_10_source1": "Stakeholders",
        "3_vd_dashboard_item_1_title": "Indicator 3 : Map title to be placed here",
        "3_vd_dashboard_item_1_footer": "The designations employed and the presentation of material in the maps do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers. South Sudan declared its independence on July 9, 2011. Due to data availability, the assessment presented in the map for Sudan and South Sudan reflects the situation up to 2011 for the former Sudan.",
        "3_vd_dashboard_item_2_title": "Indicator 3 : Chart title to be placed here",
        "3_vd_dashboard_item_3_title": "Indicator 3 : Chart title to be placed here",
        "3_vd_dashboard_item_4_title": "Indicator 3 : Chart title to be placed here",
        "3_vd_dashboard_item_1_uid": "Indicator3",
        "3_vd_dashboard_item_2_uid": "Indicator3",
        "3_vd_dashboard_item_3_uid": "Indicator3",
        "3_vd_dashboard_item_4_uid": "Indicator3",
        "3_dd_table_title_col_1": "Domain",
        "3_dd_table_title_col_2": "Country",
        "3_dd_table_title_col_3": "Element",
        "3_dd_table_title_col_4": "Indicator and Rating",
        "3_dd_table_title_col_5": "Period",
        "3_dd_table_title_col_6": "Percentage"



    }
});